name: Windows

on:
  push:
  pull_request:
    branches:
      - msvc

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]
        kind: [static, shared]
        arch: [x64, x86]
        vs_runtime: [MT, MD]

    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Windows-${{ matrix.os }}-${{ matrix.kind }}-${{ matrix.arch }}-${{ matrix.vs_runtime }}
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
        with:
          minimum-size: 8GB
          maximum-size: 32GB
          disk-root: "D:"

      - name: Tests
        run: |
          xmake f --vs_runtime=${{ matrix.vs_runtime }} --kind=${{ matrix.kind }} --arch=${{ matrix.arch }}
          xmake -vD
